repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        exclude: ^townhall/myapi/migrations/
        language_version: python3.11
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,E701']
        exclude: ^townhall/myapi/migrations/
