repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        exclude: ^townhall/myapi/migrations/
        language_version: python3.12
        pass_filenames: false
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,E701']
        exclude: ^townhall/myapi/migrations/
        pass_filenames: false
  - repo: local
    hooks:
      - id: run-tests
        name: Run All Tests Before Commit
        entry: python3 townhall/manage.py test tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true


