# Generated by Django 5.0.6 on 2024-08-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='myapi.volunteer'),
        ),
    ]
