# Generated by Django 5.0.6 on 2024-08-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_opportunity_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='age',
        ),
    ]
