# Generated by Django 5.0.6 on 2024-08-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_post_comment'),
        ('myapi', '0006_remove_organization_description_and_more'),
    ]

    operations = [
    ]
