# Generated by Django 5.0.6 on 2024-08-17 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_remove_organization_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
