# Generated by Django 5.1 on 2024-08-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_merge_20240823_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$IcC9UM6Hm9DME1TWAapDOn$+EZ0HSFNN1DtAJxTbdbog15jQAcQo4JOb2hkiWLKdus=', max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
