# Generated by Django 5.0.6 on 2024-08-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_post_image'),
        ('myapi', '0008_rename_time_opportunity_start_time_and_more'),
    ]

    operations = [
    ]
