# Generated by Django 5.1 on 2024-08-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_volunteer_is_active_volunteer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sG3en6vVwUKPiI9sSnzxBu$R5wBJ5MFXYiKfB3OeA43Scv+f14ubnTAV/7XCZWMSes=', max_length=128),
        ),
    ]
