# Generated by Django 5.1 on 2024-08-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alter_volunteer_password'),
        ('myapi', '0009_merge_20240827_2017'),
    ]

    operations = [
    ]
