# Generated by Django 5.1 on 2024-08-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_merge_20240829_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.volunteer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$WVxFIEFKq8AVgOKjzMH31D$bTcP82YroQl3LLNTbtF/6h2+l1v/nASYWwhgcvP0KSw=', max_length=128),
        ),
    ]
