# Generated by Django 5.1 on 2024-09-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_opportunity_organization_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Cmt9XwxVrhUCRlkFuD3Owd$vgGq9kL9mwnpQXe6Z+GiJ2aTv5SleZoXPnKpvwzp+NM=', max_length=128),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='myapi.volunteer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='myapi.volunteer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organization')),
            ],
        ),
    ]
