# Generated by Django 5.0.6 on 2024-10-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_opportunity_organization_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$kAOMzXliFzgrJuWAGrx42I$Ni/SDnsEoa8DWQ8TuGRoQbKnH6TZnTiSGaGkbg8vtpU=', max_length=128),
        ),
    ]
