# Generated by Django 5.1 on 2024-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JE9az6Prob1C9WBL6O2YPv$vJZ5H1FYkHbAOFkf3Nd24d6y5iATdvaO7UcfRqSh2Ig=', max_length=128),
        ),
    ]
