# Generated by Django 5.0.6 on 2024-10-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_volunteer_email_alter_volunteer_password'),
        ('myapi', '0016_alter_task_status_alter_volunteer_password'),
    ]

    operations = [
    ]
