# Generated by Django 5.0.6 on 2024-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_alter_volunteer_password_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='partipants',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipent_id',
            new_name='recipent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$uBbdA2CU053v3UfMdsZi0b$BrSZSZA9Vr9z0UHv9QU9Jc/14TGD4Mml+DpOY/x3Jlk=', max_length=128),
        ),
    ]
