# Generated by Django 5.0.6 on 2024-10-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_merge_20241009_1557'),
        ('myapi', '0018_rename_partipants_chat_participants_and_more'),
    ]

    operations = [
    ]
