# Generated by Django 5.1.5 on 2025-01-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_alter_volunteer_password_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$KnZJjM4CShDit7ab2D11IO$Cv3SwXNaL0yi0p7+ab90IHbRX/0KKWzHvSSZk8aiqBs=', max_length=128),
        ),
    ]
