# Generated by Django 5.0.6 on 2025-01-12 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_alter_volunteer_password_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$rkksrUqmJg0VIkijT0flKG$G0CQ65sG4DAHHmEljmOcOoCGVPjzXfOk6Syz1CQurWI=', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='community_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.community'),
        ),
    ]
