# Generated by Django 5.1.6 on 2025-03-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_alter_volunteer_password_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$frsIbJCmLOQOfcoEMFaiFE$ErvvKzpvaIZx3ZyPgPD+QleZ9YfysGYxkOBiC0HwpiQ=', max_length=128),
        ),
    ]
