# Generated by Django 5.1.5 on 2025-02-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$S9WUbheMje9pQPeWersb0L$Lqc7x8tHzupVkE6ZBz1i1h3DOzu2dfmQSNLyCjDzN/g=', max_length=128),
        ),
    ]
