# Generated by Django 5.0.6 on 2025-01-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_alter_project_community_id_alter_volunteer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='community_id',
            new_name='community',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$rUorZKu4Bj2jBxFW7GbnrU$QWm6tAYXVdeBRIcusgYNuZ/XxcYnclE4n0Kl+UnufP0=', max_length=128),
        ),
    ]
