# Generated by Django 5.1.5 on 2025-02-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$jpQ0nh1hCGhw2O88AbB8cZ$ju+1WVLc+cS+A8b34ngc+XsM7Q6GaBWStpd9fH7aU1s=', max_length=128),
        ),
    ]
