# Generated by Django 5.0.6 on 2025-03-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_rename_community_id_project_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$0xQXW08PRiS5qQ7I42XEUD$RyDdRJzKG32aHY/vTRPXGsg7qKaDVtO639Ae7fhSfbY=', max_length=128),
        ),
    ]
