# Generated by Django 5.1.6 on 2025-03-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_rename_community_id_project_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bunOlw8L5fQ6MVVEqkMhgy$KgQdAVdD2kp+SF95Ogv3KxMTRrGG9sntcfSy4doNvT8=', max_length=128),
        ),
    ]
