# Generated by Django 5.1.5 on 2025-02-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$XWGDyNle34SLdMoWCPtJwv$jCGRgiaSdh8U/3rhA4rbC5efNn9WTgmBI1SHMFBUZns=', max_length=128),
        ),
    ]
