# Generated by Django 5.0.6 on 2025-03-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_alter_comment_user_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$cqOOaQU5EQkjBHM2P6EmPb$CESatJ/+vkLxTt9QOA8TFaq28Rv7fxUZW1G2IqT1AzE=', max_length=128),
        ),
    ]
