# Generated by Django 5.1.6 on 2025-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hzFUPaN1bhye1NlNC7qvuJ$yzf+BOOgbBgGL1WhFMm/kRv+hLY8Z0BF57dBFG5V62c=', max_length=128),
        ),
    ]
