# Generated by Django 5.0.6 on 2025-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_volunteer_about_me_volunteer_other_networks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$gonT2Ofx65sPzc6EQgNKog$81E8KfN2yuxMfsCJmLupBeoWqzRtNq57H+BFeETkujQ=', max_length=128),
        ),
    ]
