# Generated by Django 5.0.6 on 2025-04-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_volunteer_profile_image_alter_volunteer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$qPAakZPBdBPl0ZAX21MiYs$wBIAAmZbvZT3WolJ5DcqV6o+csO2X3sPDo5+RsI6Vw0=', max_length=128),
        ),
    ]
