# Generated by Django 5.0.6 on 2025-04-29 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_post_likes_alter_volunteer_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$dcHkUM0NMzRGcLFhC4JN3z$7g/tdP4ccGzcVfTiVjM5j6vWgdcvCEsvbzCYLzO643Q=', max_length=128),
        ),
    ]
