# Generated by Django 5.0.6 on 2025-04-29 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_post_liked_by_alter_volunteer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$GD8LShpPiXDtS30gfApnfK$5VfD4+scYTd1ZvqHw86QLGxFbvSigyv/3Mi+3pIudVU=', max_length=128),
        ),
    ]
