# Generated by Django 5.0.6 on 2025-04-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_volunteer_last_login_alter_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='myapi.volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$hPN73oBsigVJebTqm8Cwv1$339uG1UgodmsN5u0UCNwqs52xJSkT10TcPVG9XckV/0=', max_length=128),
        ),
    ]
