name: Code linting with Flake8

on:
  pull_request:
    branches:
      '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r townhall/requirements.txt

    - name: Run Flake8
      run: flake8 --max-line-length=88 --extend-ignore=E203,E701 --exclude "townhall/myapi/migrations/"
